<script lang="ts" context="module">
	// {@html} is safe here because it’s generated by Shiki
	/* eslint-disable svelte/no-at-html-tags */

	export interface ShikiOptions {
		/** Set Shiki themes and preloaded langs */
		highlighter: shikiJS.HighlighterOptions;
		/** Shiki CDN root (default: "/assets/shiki") */
		cdn?: string;
	}

	export const SHIKI_DEFAULT_THEME: shikiJS.Theme = 'material-theme-palenight';
	export const SHIKI_DEFAULT_LANGS: shikiJS.Lang[] = ['bash', 'html', 'css', 'shell', 'javascript', 'svelte'];
	export const SHIKI_LINES_RE = /<\s*span\s+class="line"/g;
	export const SHIKI_ROOT_STYLE_RE = /style="([^"]+)/;

	/**
	 * global cached shiki highlighters
	 * this should stay at the module level so instances can share one cache
	 */
	export const cachedHighlighters = new Map<string, shikiJS.Highlighter>();
</script>

<script lang="ts">
	import * as shikiJS from 'shiki';
	import { omit } from './lib/props.js';

	// props

	/** highlighted code to display */
	export let code: string;
	/** code language */
	export let lang: shikiJS.Lang | undefined;
	/** show line numbers? (default: `false`) */
	export let lineNumbers = false;
	/** edit if line numbers don’t start at `1` */
	export let startingLineNumber = 1;
	/** show copy button? (default: `true`) */
	export let showCopy = true;
	/** configure Shiki */
	export let shiki: ShikiOptions = {
		highlighter: {
			theme: SHIKI_DEFAULT_THEME,
			langs: SHIKI_DEFAULT_LANGS,
		},
		cdn: '/assets/shiki',
	};

	// state
	let highlighter: shikiJS.Highlighter | undefined;

	// methods
	function handleCopy(): void {
		if (code) {
			navigator.clipboard.writeText(code);
		}
	}

	// reactivity
	$: highlighterID = JSON.stringify({ theme: shiki?.highlighter?.theme ?? SHIKI_DEFAULT_THEME, langs: shiki?.highlighter?.langs ?? SHIKI_DEFAULT_LANGS }); // not perfect, but this is serializable enough to work for most cases
	$: {
		shikiJS.setCDN(shiki?.cdn ?? '/assets/shiki');
	}
	$: {
		if (!highlighter) {
			if (cachedHighlighters.has(highlighterID)) {
				highlighter = cachedHighlighters.get(highlighterID);
			} else {
				shikiJS.getHighlighter({ theme: SHIKI_DEFAULT_THEME, langs: SHIKI_DEFAULT_LANGS, ...shiki.highlighter }).then((h) => {
					highlighter = h;
					cachedHighlighters.set(highlighterID, h);
				});
			}
		}
	}
	$: codeHtml = highlighter ? highlighter.codeToHtml(code, { lang }) : undefined;
	$: lineMatches = codeHtml ? codeHtml.match(SHIKI_LINES_RE) : null;
	$: lineCount = lineMatches ? lineMatches.length : 0;
	$: rootStyleMatch = codeHtml ? codeHtml.match(SHIKI_ROOT_STYLE_RE) : null;
	$: rootStyle = rootStyleMatch?.[1];
</script>

<div class="wrapper">
	{#if showCopy}
		<div class="menu" role="menu">
			<button class="copy-button" type="button" on:click={handleCopy} aria-label="copy"
				><svg class="copy-icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
					><path
						d="M9,2 C7.89543,2 7,2.89543 7,4 L7,6 L9,6 L9,4 L20,4 L20,15 L18,15 L18,17 L20,17 C21.1046,17 22,16.1046 22,15 L22,4 C22,2.89543 21.1046,2 20,2 L9,2 Z M4,7 C2.89543,7 2,7.89543 2,9 L2,20 C2,21.1046 2.89543,22 4,22 L15,22 C16.1046,22 17,21.1046 17,20 L17,9 C17,7.89543 16.1046,7 15,7 L4,7 Z M4,9 L15,9 L15,20 L4,20 L4,9 Z"
						fill="currentColor"
					/></svg
				></button
			>
		</div>
	{/if}
	<div class="window">
		{#if lineNumbers}
			<div class="linenumbers" style={rootStyle}>
				{#each Array(lineCount) as _, i}<div class="linenumber">{startingLineNumber + i}</div>{/each}
			</div>
		{/if}
		<div class="code" {...omit($$props, ['code', 'copiedDuration', 'copiedText', 'copyText', 'lang', 'lineNumbers', 'showCopy', 'shiki', 'startingLineNumber'])}>
			{#if codeHtml}{@html codeHtml}{:else}<pre><code>{code}</code></pre>{/if}
		</div>
	</div>
</div>

<style lang="scss">
	@use '../tokens' as *;

	.wrapper {
		@include typography('typography.mono');

		border-radius: token('size.s.radius');
		color: token('color.white');
		display: flex;
		max-width: 100%;
		overflow: hidden;
		position: relative;

		:global(.shiki) {
			font-size: token('size.s.textSize');
			margin: 0;
			padding: token('size.m.padding');
			width: 100%;
		}
	}

	.code {
		box-sizing: border-box;
		display: flex;
		overflow-x: auto;
		width: 100%;
	}

	.copy-button {
		align-items: center;
		background: transparent;
		border-radius: token('size.m.radius');
		border: none;
		color: token('color.white');
		cursor: pointer;
		display: flex;
		height: 2.5rem;
		justify-content: center;
		padding: 0;
		opacity: 0.7;
		width: 2.5rem;

		&:hover,
		&:focus-visible {
			opacity: 1;
		}

		&:active {
			opacity: 0.7;
		}
	}

	.copy-icon {
		height: 1rem;
		width: 1rem;
	}

	.inner {
		padding-right: token('size.s.padding');
	}

	.linenumber {
		opacity: 0.5;
	}

	.linenumbers {
		padding-left: token('size.m.padding');
		padding-top: token('size.m.padding');
		text-align: right;
	}

	.menu {
		right: 0;
		top: 0;
		position: absolute;
		z-index: token('layer.nav');
	}

	.window {
		display: flex;
		width: 100%;
	}
</style>
